### ISSUE TITLE
Chromecast Adapter doesn't work

### ISSUE THREAD

**Issue by hellermartin** [ioBroker/ioBroker.sayit#106]
Hi there,

for me the adapter is also not working. I'm using the current version of iobroker with Node.js: v12.18.4.
I think the "http://**null**:8082...." is the problem. The raspi is running as DHCP client.

Here is the log:

2020-10-04 10:36:33.449 - info: javascript.0 (1452) Stop script script.js.speak.example
--
2020-10-04 10:36:33.474 - info: javascript.0 (1452) Start javascript script.js.speak.example
2020-10-04 10:36:33.507 - info: javascript.0 (1452) script.js.speak.example: registered 0 subscriptions and 0 schedules
2020-10-04 10:36:33.519 - info: sayit.0 (1714) saying: /opt/iobroker/node_modules/iobroker.sayit/gong.mp3
2020-10-04 10:36:33.529 - info: sayit.0 (1714) Set "chromecast.0.Familienzimmer.player.announcement to {"url":"http://null:8082/state/sayit.0.tts.mp3","volume":11}
2020-10-04 10:36:33.536 - info: chromecast.0 (5452) Familienzimmer - Try to launch default player
2020-10-04 10:36:42.530 - info: sayit.0 (1714) saying: Trockner fertig
2020-10-04 10:36:42.535 - info: sayit.0 (1714) Set "chromecast.0.Familienzimmer.player.announcement to {"url":"http://null:8082/state/sayit.0.tts.mp3","volume":"38"}
2020-10-04 10:36:42.541 - info: chromecast.0 (5452) Familienzimmer - Try to launch default player
2020-10-04 10:36:52.854 - info: chromecast.0 (5452) Familienzimmer - Connected player
2020-10-04 10:36:52.855 - info: chromecast.0 (5452) Familienzimmer - Default player lauched
2020-10-04 10:36:52.855 - info: chromecast.0 (5452) Familienzimmer - Try to play announcement - "http://null:8082/state/sayit.0.tts.mp3"
2020-10-04 10:36:52.856 - info: chromecast.0 (5452) Familienzimmer - Try to play url - http://null:8082/state/sayit.0.tts.mp3
2020-10-04 10:36:52.861 - info: chromecast.0 (5452) Familienzimmer - Connected player
2020-10-04 10:36:52.863 - info: chromecast.0 (5452) Familienzimmer - Default player lauched
2020-10-04 10:36:52.863 - info: chromecast.0 (5452) Familienzimmer - Try to play announcement - "http://null:8082/state/sayit.0.tts.mp3"
2020-10-04 10:36:52.864 - info: chromecast.0 (5452) Familienzimmer - Try to play url - http://null:8082/state/sayit.0.tts.mp3
2020-10-04 10:36:52.911 - info: chromecast.0 (5452) Familienzimmer - set volume to 38
2020-10-04 10:36:52.922 - info: chromecast.0 (5452) Familienzimmer - set volume to 11
2020-10-04 10:36:54.330 - info: chromecast.0 (5452) Familienzimmer - Closing mediaInfo
2020-10-04 10:36:54.332 - error: chromecast.0 (5452) Familienzimmer - Error playing playlist - Error: Error: getaddrinfo ENOTFOUND null
at ClientRequest. (/opt/iobroker/node_modules/castv2-player/lib/mediaInfo.js:80:98)
at ClientRequest.emit (events.js:315:20)
at Socket.socketErrorListener (_http_client.js:426:9)
at Socket.emit (events.js:315:20)
at emitErrorNT (internal/streams/destroy.js:92:8)
at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
at processTicksAndRejections (internal/process/task_queues.js:84:21)
2020-10-04 10:36:54.333 - error: chromecast.0 (5452) Familienzimmer - Could not play announcement: Error: Error: getaddrinfo ENOTFOUND null
2020-10-04 10:36:54.445 - info: chromecast.0 (5452) Familienzimmer - Closing mediaInfo
2020-10-04 10:36:54.447 - error: chromecast.0 (5452) Familienzimmer - Error playing playlist - Error: Error: getaddrinfo ENOTFOUND null
at ClientRequest. (/opt/iobroker/node_modules/castv2-player/lib/mediaInfo.js:80:98)
at ClientRequest.emit (events.js:315:20)
at Socket.socketErrorListener (_http_client.js:426:9)
at Socket.emit (events.js:315:20)
at emitErrorNT (internal/streams/destroy.js:92:8)
at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
at processTicksAndRejections (internal/process/task_queues.js:84:21)
2020-10-04 10:36:54.448 - error: chromecast.0 (5452) Familienzimmer - Could not play announcement: Error: Error: getaddrinfo ENOTFOUND null
2020-10-04 10:37:02.695 - info: chromecast.0 (5452) 55PUS6551/12 - Connected client
2020-10-04 10:41:53.008 - info: chromecast.0 (5452) Familienzimmer - Detached player
2020-10-04 10:41:53.009 - info: chromecast.0 (5452) Familienzimmer - Detached player

**Comment by Apollon77** [comment]
bitte die Settings des Adapters zeigen,m vor allem der webserver der definiert ist

**Comment by hellermartin** [comment]
Die Settings beinhalten die IP des LAN Interface des Pi, dass auf DHCP läuft.

**Comment by Apollon77** [comment]
zeig mal bitte screenshot der konfig
