### ISSUE TITLE
Compatibility issue(?) with js-controller 5.x

### ISSUE THREAD

**Issue by raintonr** [ioBroker/ioBroker.sayit#261]
After upgrading to js-controller 5.x get this:

```
2023-05-21 11:10:29.141  - info: host.pl instance system.adapter.sayit.0 started with pid 10094
2023-05-21 11:10:30.577  - error: host.pl Caught by controller[0]: /opt/iobroker/node_modules/iobroker.sayit/main.js:77
2023-05-21 11:10:30.577  - error: host.pl Caught by controller[0]:         adapter.log.error('Could not create Storage directory: ' + err);
2023-05-21 11:10:30.578  - error: host.pl Caught by controller[0]:                     ^
2023-05-21 11:10:30.578  - error: host.pl Caught by controller[0]: TypeError: Cannot read properties of undefined (reading 'error')
2023-05-21 11:10:30.578  - error: host.pl Caught by controller[0]:     at startAdapter (/opt/iobroker/node_modules/iobroker.sayit/main.js:77:21)
2023-05-21 11:10:30.578  - error: host.pl Caught by controller[0]:     at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.sayit/main.js:729:5)
```

**Comment by raintonr** [comment]
Ah... seems this is fixed with 3.0.5. All good :)
