### ISSUE TITLE
Sayit funktioniert bei mir seit Version 4.0.1 überhaupt nicht mehr.

### ISSUE THREAD

**Issue by wendy2702** [ioBroker/ioBroker.sayit#320]
Sayit funktioniert bei mir seit Version 4.0.1 überhaupt nicht mehr. Auch meine Scripte mit Rules bringen keine Ansage mehr. Ebenfall bekomme ich keine Ansage beim Drücken des TEST Button.

Wenn ich die Instanz öffne erhalte ich diese Fehler im log:

```
2024-06-04 17:50:33.808  - info: sayit.0 (880) saying: hallo
2024-06-04 17:50:57.236  - error: sayit.0 (880) Error: The module '/opt/iobroker/node_modules/mdns/build/Release/dns_sd_bindings.node'
2024-06-04 17:51:15.571  - error: sayit.0 (880) Error: The module '/opt/iobroker/node_modules/mdns/build/Release/dns_sd_bindings.node'

```
EDIT: den Fehler oben habe ich durch ein NPM rebuild wegbekommen. Denke lag am NODEJS 20 update.
Jetzt erhalte ich das beim Öffnen der Instanz:

`2024-06-04 18:52:30.373  - error: sayit.0 (45755) Error: dns service error: unknown
`

So sehen die Einstellungen nach Update auf 4.0.1 aus:

![grafik](https://github.com/ioBroker/ioBroker.sayit/assets/33424168/e1925a2c-af55-4aa0-91b4-064130669bf2)

Wenn ich mit den Einstellungen auf Test drücke kommt das 

`2024-06-04 18:01:02.628  - error: sayit.0 (44931) Cannot control browser via vis1, because vis.0.* objects found
`

Stell ich das um auf VIS.0 (veraltet) und Drücke "Test" kommt dasselbe:

`2024-06-04 18:02:29.266  - error: sayit.0 (44981) Cannot control browser via vis1, because vis.0.* objects found`

Stell ich auf VIS-2.0 (neu) um erhalte ich das:

`2024-06-04 18:03:54.981  - error: sayit.0 (45001) Cannot control browser via vis1, because vis-2.0.* objects found`

_Ursprünglich gepostet von @wendy2702 in https://github.com/ioBroker/ioBroker.sayit/issues/269#issuecomment-2147903980_

**Comment by Apollon77** [comment]
iob fix versucht?

**Comment by wendy2702** [comment]
Als der Fehler aufgetreten ist "Ja".

Mittlerweile sind wir paar Updates weiter auf dem System und jedesmal lasse ich den nicht laufen. 

Werde ich jetzt sofort testen

**Comment by wendy2702** [comment]
Nach iob Fix ist das Verhalten bei mir unverändert.

```
mirko@iobroker:~$ iob fix
library: loaded
Library version=2024-05-24

==========================================================================

    Welcome to the ioBroker installation fixer!
    Script version: 2024-01-04

    You might need to enter your password a couple of times.

==========================================================================


==========================================================================
    Installing prerequisites (1/5)
==========================================================================

[sudo] password for mirko:
Get:1 http://security.debian.org/debian-security bookworm-security InRelease [48.0 kB]
Hit:2 http://deb.debian.org/debian bookworm InRelease
Get:3 http://deb.debian.org/debian bookworm-updates InRelease [55.4 kB]
Get:4 http://security.debian.org/debian-security bookworm-security/main Sources [99.1 kB]
Get:5 http://security.debian.org/debian-security bookworm-security/main amd64 Packages [160 kB]
Get:6 http://security.debian.org/debian-security bookworm-security/main Translation-en [96.5 kB]
Get:7 https://deb.nodesource.com/node_20.x nodistro InRelease [12.1 kB]
Get:8 https://deb.nodesource.com/node_20.x nodistro/main amd64 Packages [7936 B]
Fetched 479 kB in 1s (514 kB/s)
Reading package lists... Done

==========================================================================
    Checking ioBroker user and directory permissions (2/5)
==========================================================================

Created /etc/sudoers.d/iobroker
Fixing directory permissions...

==========================================================================
    Check and cleanup npm temporary directories (3/5)
==========================================================================

Done.

==========================================================================
    Database maintenance (4/5)
==========================================================================

Checking for uncompressed JSONL databases... This might take a while!

Compressing /opt/iobroker/iobroker-data/states.jsonl
Compressing /opt/iobroker/iobroker-data/objects.jsonl
Compressed 2 JSONL files. Done

==========================================================================
    Checking autostart (5/5)
==========================================================================

Enabling autostart...
Autostart enabled!

==========================================================================

    Your installation was fixed successfully
    Run iobroker start to start ioBroker again!

==========================================================================

mirko@iobroker:~$ iob start
```

Z.B. erzeugt diese Einstellung:

![grafik](https://github.com/ioBroker/ioBroker.sayit/assets/33424168/4906daa8-5f38-447f-ae7e-0b8e4b89696e)

Das im Log:

```
2024-06-21 09:58:46.219  - error: sayit.0 (146392) Cannot control browser via vis1, because vis-2.0.* objects found
```

**Comment by wm20320** [comment]
Krieg leider sayit auch nicht mehr zum Laufen. Solange vis-2 noch nicht aktiv war, ging die 3.0.5 noch tadellos. Jetzt, wo vis-2 auch läuft bekomme ich keine Version mehr zum Sprechen über Browser:
Node-Version: 20.15.0
JS-controller 6.0.5
Fehlermeldung bei der 4.0.1, wenn der Test-Button gedrückt wird:
` 
```
host.lue-linux
2024-06-27 15:37:00.124	warn	instance system.adapter.sayit.0 terminated due to SIGABRT
 
host.lue-linux
2024-06-27 15:37:00.124	error	Caught by controller[0]: 6: MDNSService.self.watcher.callback (/opt/iobroker/node_modules/mdns/lib/mdns_service.js:18:40)
 
host.lue-linux
2024-06-27 15:37:00.124	error	Caught by controller[0]: 5: on_resolver_done (/opt/iobroker/node_modules/mdns/lib/resolver_sequence_tasks.js:33:11)
 
host.lue-linux
2024-06-27 15:37:00.124	error	Caught by controller[0]: 4: next (/opt/iobroker/node_modules/mdns/lib/browser.js:109:21)
 
host.lue-linux
2024-06-27 15:37:00.124	error	Caught by controller[0]: 3: getaddrinfo (/opt/iobroker/node_modules/mdns/lib/resolver_sequence_tasks.js:152:14)
 
host.lue-linux
2024-06-27 15:37:00.124	error	Caught by controller[0]: 2: /opt/iobroker/node_modules/mdns/lib/resolver_sequence_tasks.js:153:7
 
host.lue-linux
2024-06-27 15:37:00.124	error	Caught by controller[0]: 1: getaddrinfo_0_11 (/opt/iobroker/node_modules/mdns/lib/resolver_sequence_tasks.js:117:21)
 
host.lue-linux
2024-06-27 15:37:00.124	error	Caught by controller[0]: ----- JavaScript stack trace -----
 
host.lue-linux
2024-06-27 15:37:00.123	error	Caught by controller[0]: 6: 0x1961df6 [io.sayit.0]
 
host.lue-linux
2024-06-27 15:37:00.123	error	Caught by controller[0]: 5: 0xf57315 v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) [io.sayit.0]
 
host.lue-linux
2024-06-27 15:37:00.123	error	Caught by controller[0]: 4: 0xf56e4d [io.sayit.0]
 
host.lue-linux
2024-06-27 15:37:00.123	error	Caught by controller[0]: 3: 0xf565df v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo) [io.sayit.0]
 
host.lue-linux
2024-06-27 15:37:00.123	error	Caught by controller[0]: 2: 0xbe78aa [io.sayit.0]
 
host.lue-linux
2024-06-27 15:37:00.123	error	Caught by controller[0]: 1: 0xcba2d7 node::Assert(node::AssertionInfo const&) [io.sayit.0]
 
host.lue-linux
2024-06-27 15:37:00.123	error	Caught by controller[0]: ----- Native stack trace -----
 
host.lue-linux
2024-06-27 15:37:00.123	error	Caught by controller[0]: # Assertion failed: args[4]->IsUint32()
 
host.lue-linux
2024-06-27 15:37:00.123	error	Caught by controller[0]: # io.sayit.0[6196]: void node::cares_wrap::{anonymous}::GetAddrInfo(const v8::FunctionCallbackInfo<v8::Value>&) at ../src/cares_wrap.cc:1575
 
host.lue-linux
2024-06-27 15:37:00.123	error	Caught by controller[0]: *** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
 
host.lue-linux
2024-06-27 15:37:00.123	error	Caught by controller[0]: *** WARNING *** Please fix your application to use the native API of Avahi!
 
host.lue-linux
2024-06-27 15:37:00.123	error	Caught by controller[0]: *** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
 
host.lue-linux
2024-06-27 15:37:00.123	error	Caught by controller[0]: *** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
 
host.lue-linux
2024-06-27 15:37:00.123	error	Caught by controller[0]: *** WARNING *** Please fix your application to use the native API of Avahi!
 
host.lue-linux
2024-06-27 15:37:00.122	error	Caught by controller[0]: *** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
```
`
und
` 
```
host.lue-linux
2024-06-27 15:37:34.545	info	instance system.adapter.sayit.0 terminated with code null ()
 
host.lue-linux
2024-06-27 15:37:34.545	warn	instance system.adapter.sayit.0 terminated due to SIGKILL
 
host.lue-linux
2024-06-27 15:37:34.475	info	stopInstance timeout 1000 system.adapter.sayit.0 killing pid 8343
 
sayit.0
2024-06-27 15:37:33.983	info	Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
 
sayit.0
2024-06-27 15:37:33.477	info	stopping...
 
host.lue-linux
2024-06-27 15:37:33.474	info	stopInstance system.adapter.sayit.0 (force=false, process=true)
 
sayit.0
2024-06-27 15:37:33.128	error	Cannot write file: TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object
 
sayit.0
2024-06-27 15:37:32.973	info	Upload announce mp3 files
 
sayit.0
2024-06-27 15:37:32.947	info	starting. Version 4.0.1 in /opt/iobroker/node_modules/iobroker.sayit, node: v20.15.0, js-controller: 6.0.5
 
host.lue-linux
2024-06-27 15:37:30.606	info	instance system.adapter.sayit.0 started with pid 8343
 
host.lue-linux
2024-06-27 15:37:00.124	info	Restart adapter system.adapter.sayit.0 because enabled
```
`
iob fix habe ich gemacht, reboot auch ...

Vieleicht helfen diese Dinge weiter? Oder gibt es einen Tipp, was den Fehler verursacht?

Danke! 

(diesen Beitrag habe ich auch im iobroker-Forum gepostet)

**Comment by wendy2702** [comment]
Wenn ich den "Button" in der Instanz betätige passiert das:

```
2024-07-05 14:06:59.264  - info: sayit.0 (235478) starting. Version 4.0.1 in /opt/iobroker/node_modules/iobroker.sayit, node: v20.15.0, js-controller: 5.0.19
2024-07-05 14:06:59.309  - info: sayit.0 (235478) Upload announce mp3 files
2024-07-05 14:07:24.491  - info: javascript.0 (147632) script.js.common.Ansagen.Voice_Feedback_Garagentor_Rechts: Executed sayit.2: [Volume - 60]: Garagentor rechts auf
2024-07-05 14:07:29.212  - info: javascript.0 (147632) script.js.common.Ansagen.Voice_Feedback_Garagentor_Rechts: Executed sayit.2: [Volume - 60]: Garagentor rechts zu
2024-07-05 14:07:48.342  - error: sayit.0 (235478) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2024-07-05 14:07:48.343  - error: sayit.0 (235478) unhandled promise rejection: Cannot read properties of null (reading 'engine')
2024-07-05 14:07:48.345  - error: sayit.0 (235478) TypeError: Cannot read properties of null (reading 'engine')
    at processMessage (/opt/iobroker/node_modules/iobroker.sayit/main.js:178:43)
    at AdapterClass.<anonymous> (/opt/iobroker/node_modules/iobroker.sayit/main.js:90:34)
2024-07-05 14:07:48.345  - error: sayit.0 (235478) Cannot read properties of null (reading 'engine')
2024-07-05 14:07:48.348  - info: sayit.0 (235478) stopping...
2024-07-05 14:07:48.349  - info: sayit.0 (235478) terminating
2024-07-05 14:07:48.350  - warn: sayit.0 (235478) Terminated (UNCAUGHT_EXCEPTION): Without reason
2024-07-05 14:07:48.851  - info: sayit.0 (235478) terminating
2024-07-05 14:07:49.103  - error: host.iobroker instance system.adapter.sayit.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2024-07-05 14:07:49.103  - info: host.iobroker Restart adapter system.adapter.sayit.0 because enabled
2024-07-05 14:08:20.269  - info: host.iobroker instance system.adapter.sayit.0 started with pid 235494
```

**Comment by bahnuhr** [comment]
hab das gleiche Problem und eben auch ein issue eröffnet.
Da muss sich wirklich mal jemand drum kümmern.

Wenn ich als instanz-Nr. die FFFFFFFF kommt die Ansage; aber halt auf allen Geräten !
Das ist so nicht hilfreich.

**Comment by GermanBluefox** [comment]
Please test v4.0.2

**Comment by wendy2702** [comment]
Hi,

works with 4.0.2

Thanks for working on it!

**Comment by wendy2702** [comment]
Hi,

works with 4.0.2

Thanks for working on it!
