### ISSUE TITLE
sayit adapter error message

### ISSUE THREAD

**Issue by hilde0407** [ioBroker/ioBroker.sayit#327]
I have reinstalled my IOBroker and imported a backup. Since then, the sayit adapter no longer works!
The following configuration:
Platform: linux
RAM: 7.7 GB
Node.js: v20.15.1
NPM: 10.7.0
*Describe the bug**  

`
host.iobroker | 2024-07-09 17:15:17.384 | info | Do not restart adapter system.adapter.sayit.0 because disabled or deleted
-- | -- | -- | --
host.iobroker | 2024-07-09 17:15:17.383 | error | instance system.adapter.sayit.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
host.iobroker | 2024-07-09 17:15:17.383 | error | Caught by controller[2]: at processImmediate (node:internal/timers:478:21)
host.iobroker | 2024-07-09 17:15:17.383 | error | Caught by controller[2]: at Immediate.<anonymous> (file:///opt/iobroker/node_modules/@iobroker/db-states-redis/src/lib/states/statesInRedisClient.ts:383:37)
host.iobroker | 2024-07-09 17:15:17.383 | error | Caught by controller[2]: at change (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:10948:34)
host.iobroker | 2024-07-09 17:15:17.383 | error | Caught by controller[2]: at AdapterClass.emit (node:domain:488:12)
host.iobroker | 2024-07-09 17:15:17.383 | error | Caught by controller[2]: at AdapterClass.emit (node:events:519:28)
host.iobroker | 2024-07-09 17:15:17.383 | error | Caught by controller[2]: at AdapterClass.<anonymous> (/opt/iobroker/node_modules/iobroker.sayit/main.js:90:34)
host.iobroker | 2024-07-09 17:15:17.383 | error | Caught by controller[2]: at processMessage (/opt/iobroker/node_modules/iobroker.sayit/main.js:178:43)
host.iobroker | 2024-07-09 17:15:17.382 | error | Caught by controller[2]: TypeError: Cannot read properties of null (reading 'engine')
host.iobroker | 2024-07-09 17:15:17.381 | error | Caught by controller[1]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
sayit.0 | 2024-07-09 17:15:17.343 | info | terminating
sayit.0 | 2024-07-09 17:15:16.842 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
sayit.0 | 2024-07-09 17:15:16.841 | info | terminating
sayit.0 | 2024-07-09 17:15:16.841 | info | stopping...
sayit.0 | 2024-07-09 17:15:16.829 | error | Cannot read properties of null (reading 'engine')
sayit.0 | 2024-07-09 17:15:16.829 | error | TypeError: Cannot read properties of null (reading 'engine') at processMessage (/opt/iobroker/node_modules/iobroker.sayit/main.js:178:43) at AdapterClass.<anonymous> (/opt/iobroker/node_modules/iobroker.sayit/main.js:90:34) at AdapterClass.emit (node:events:519:28) at AdapterClass.emit (node:domain:488:12) at change (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:10948:34) at Immediate.<anonymous> (file:///opt/iobroker/node_modules/@iobroker/db-states-redis/src/lib/states/statesInRedisClient.ts:383:37) at processImmediate (node:internal/timers:478:21)
sayit.0 | 2024-07-09 17:15:16.711 | error | unhandled promise rejection: Cannot read properties of null (reading 'engine')
sayit.0 | 2024-07-09 17:15:16.711 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
sayit.0 | 2024-07-09 17:15:14.511 | error | Error: dns service error: unknown

**Versions:**  
 - Adapter version: <4.01>
 - JS-Controller version: <6.06> 
 - Node version: <20.15.1> 
 - Operating system: <debian bullseye>

**Comment by GermanBluefox** [comment]
Please retest with 4.0.5
