### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by cimba007** [ioBroker/ioBroker.sayit#33]
I just started with ioBroker today but this sounds just wrong:

```
$ ./iobroker add sayit
npm install iobroker.sayit --production --prefix "/opt/iobroker" (System call)
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/6.13.1"gyp WARN EACCES attempting to reinstall using temporary dev dir "/opt/iobroker/node_modules/authenticate-pam/.node-gyp"

../authenticate_pam.cc:30:31: fatal error: security/pam_appl.h: Datei oder Verzeichnis nicht gefunden #include <security/pam_appl.h>
                               ^
compilation terminated.

make: *** [Release/obj.target/authenticate_pam/authenticate_pam.o] Fehler 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)

gyp ERR! stack     at emitTwo (events.js:106:13)gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Linux 4.9.59-v7+

gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"gyp ERR! cwd /opt/iobroker/node_modules/authenticate-pam
gyp ERR! node -v v6.13.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 

npm
 WARN optional SKIPPING OPTIONAL DEPENDENCY: authenticate-pam@1.0.2 (node_modules/authenticate-pam):npm WARN optional
 SKIPPING OPTIONAL DEPENDENCY: authenticate-pam@1.0.2 install: `node-gyp rebuild`npm WARN 
optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
host.ioBroker-Pi install adapter sayit
npm install --production (System call) in "/opt/iobroker/node_modules/iobroker.sayit"
gyp
 
WARN EACCES
 user "root" does not have permission to access the dev dir "/root/.node-gyp/6.13.1"gyp WARN EACCES attempting to reinstall using temporary dev dir "/opt/iobroker/node_modules/iobroker.sayit/node_modules/mdns/.node-gyp"

```

**Comment by cimba007** [comment]
Somehow it still did the installation ..

**Comment by Apollon77** [comment]
Yes, because these errors happened for "optional dependecies".
In general the warnings mean that some rights are incorrect. SOmetimes you also need to use "sudo" when you are root to have really correct rights and such

**Comment by cimba007** [comment]
Just wanted to leave a small feedback: All is working well! Even sending "text" to my google home mini is working! Keep the good work going!
