### ISSUE TITLE
sayit >1.6.7 und MediaPlayer24 nicht FTP

### ISSUE THREAD

**Issue by UweRP** [ioBroker/ioBroker.sayit#43]
Seid 1.6.8 erfolgt keine Sprachausgabe mehr über MediaPlayer24. Betroffen ist die **nicht** FTP Ausgabe.
Ich konnte folgende Fehlermeldung finden:
`2018-06-08 11:18:31.345  - [32minfo[39m: sayit.3 saying: Sprich einen Text zu mir!
2018-06-08 11:18:31.345  - [31merror[39m: sayit.3 uncaught exception: callback is not defined
2018-06-08 11:18:31.345  - [31merror[39m: sayit.3 ReferenceError: callback is not defined
    at uploadToStates (C:\ioBroker\node_modules\iobroker.sayit\lib\speech2device.js:31:17)
    at sayItMP24 (C:\ioBroker\node_modules\iobroker.sayit\lib\speech2device.js:234:9)
    at sayIt (C:\ioBroker\node_modules\iobroker.sayit\main.js:399:17)
    at Adapter.<anonymous> (C:\ioBroker\node_modules\iobroker.sayit\main.js:36:13)
    at emitTwo (events.js:106:13)
    at Adapter.emit (events.js:191:7)
    at Immediate.<anonymous> (C:\ioBroker\node_modules\iobroker.js-controller\lib\adapter.js:3429:38)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)`

**Comment by UweRP** [comment]
![sayit](https://user-images.githubusercontent.com/17329042/41198547-13bc3394-6c80-11e8-8c56-42c891d6740f.jpg)

**Comment by UweRP** [comment]
Ich habe gerade die Version 1.7.0 installiert, mit dem gleichen Ergebnis. Also keine Sprachausgabe und Fehlermeldung.
Bin jetzt wieder zurück auf die Version 1.6.7 damit funktioniert die Sprachausgabe dann wieder.

**Comment by UweRP** [comment]
Könnte es mit der node Version zusammen hängen? Benutze aktuell
Node.js 6.14.3 | Boron | 2018-06-12 | 5.1.281.111 | 3.10.10
unter Windows 10 64x

**Comment by BuZZy1337** [comment]
Bitte nochmal von Github installieren und erneut versuchen.
(Siehe https://forum.iobroker.net/post/233427 für mehr Informationen)

Duplicate #43
