### ISSUE TITLE
SayIt bricht ab nach update auf JS-Conroller 3.1.3

### ISSUE THREAD

**Issue by Michaelnorge** [ioBroker/ioBroker.sayit#92]
Ich benutze 2 Instanzen von SayIt (Fehler allerdings auch bei nur einer Instanz)
Wenn mein GoogleHome von ioBroker ein Sprachbefehl bekommt, terminiert sich die Instanz mit folgender Fehlermeldung:

`

2020-05-10 09:12:04.834 - info: sayit.1 (10341) stopping...
--
2020-05-10 09:12:04.907 - error: sayit.0 (9891) unknown user "undefined"
2020-05-10 09:12:04.911 - error: sayit.0 (9891) uncaught exception: Cannot read property 'state' of undefined
2020-05-10 09:12:04.914 - error: sayit.0 (9891) TypeError: Cannot read property 'state' of undefined
at checkState (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:4904:68)
at adapterObjects.getObject (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5012:26)
at (anonymous function).(anonymous function) (/opt/iobroker/node_modules/iobroker.objects-redis/index.js:1:93234)
at tryCatcher (/opt/iobroker/node_modules/standard-as-callback/built/utils.js:11:23)
at promise.then (/opt/iobroker/node_modules/standard-as-callback/built/index.js:19:49)
at process._tickCallback (internal/process/next_tick.js:68:7)
2020-05-10 09:12:04.916 - info: sayit.0 (9891) stopping...
2020-05-10 09:12:05.337 - info: sayit.1 (10341) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
2020-05-10 09:12:05.347 - info: sayit.1 (10341) terminating
2020-05-10 09:12:05.418 - info: sayit.0 (9891) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
2020-05-10 09:12:05.440 - info: sayit.0 (9891) terminating
2020-05-10 09:12:05.860 - error: host.raspberrypi instance system.adapter.sayit.1 terminated by request of the instance itself and will not be restarted, before user restarts it.
2020-05-10 09:12:05.860 - info: host.raspberrypi Do not restart adapter system.adapter.sayit.1 because desired by instance
2020-05-10 09:12:05.943 - error: host.raspberrypi instance system.adapter.sayit.0 terminated by request of the instance itself and will not be restarted, before user restarts it.
2020-05-10 09:12:05.943 - info: host.raspberrypi Do not restart adapter system.adapter.sayit.0 because desired by instance

`

**Comment by Apollon77** [comment]
Please use js.controller 3.1.4
